# Generated by Django 3.2.15 on 2022-09-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_par', models.CharField(max_length=30, verbose_name='ФИО родителя:')),
                ('phone', models.IntegerField(verbose_name='Телефон родителя:')),
                ('name_child', models.CharField(max_length=30, verbose_name='ФИО ребенка:')),
                ('date_birthday', models.DateField(verbose_name='Дата мероприятия:')),
                ('time_birthday_start', models.TextField(null=True, verbose_name='Время начала:')),
                ('time_birthday_end', models.TextField(null=True, verbose_name='Время завершения:')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация:')),
            ],
        ),
    ]
