# Generated by Django 3.2.15 on 2022-10-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_calendar_days_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='mainsite/static/gallery', verbose_name='Добавить фото')),
            ],
            options={
                'verbose_name': 'фото в галерею',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
