# Generated by Django 3.2.15 on 2022-10-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_gallery_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar_days',
            options={'ordering': ['date_birthday', 'time_birthday_start'], 'verbose_name': 'событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='upload',
            field=models.FileField(upload_to='mainsite/static/gallery', verbose_name='Добавить фото'),
        ),
    ]
