# Generated by Django 3.2.15 on 2022-10-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20221013_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='upload',
            field=models.FileField(upload_to='', verbose_name='Добавить фото'),
        ),
    ]
